DROP TABLE IF EXISTS users, items, bookings, comments, requests;

CREATE TABLE users (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name varchar(100) DEFAULT 'noname',
                         email varchar(100) NOT NULL,
                         CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE items (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name varchar(100) NOT NULL,
                         description text,
                         owner_id BIGINT NOT NULL,
                         available boolean,
                         request_id BIGINT
);
CREATE INDEX items_ownerId ON items(owner_id);

CREATE TABLE bookings (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       item_id BIGINT,
                       booker_id BIGINT,
                       start_time timestamp,
                       end_time timestamp,
                       status INTEGER,
                       CONSTRAINT bookings_items_fk FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);
CREATE INDEX bookings_itemId ON bookings(item_id);
CREATE INDEX bookings_bookerId ON bookings(booker_id);

CREATE TABLE comments (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        text varchar(100),
                        authorName varchar(100),
                        created timestamp,
                        item_id BIGINT,
                        CONSTRAINT comments_items_fk FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);
CREATE INDEX comments_itemId ON comments(item_id);

CREATE TABLE requests (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id BIGINT NOT NULL,
                          description varchar(100) NOT NULL UNIQUE,
                          created timestamp
);